//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoardRepComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class avisos
    {
        public int IdAviso { get; set; }
        public string NomeAviso { get; set; }
        public string MsgAviso { get; set; }
        public Nullable<System.DateTime> DataAviso { get; set; }
    }
}
