//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoardRepComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campanhas
    {
        public int IdCampanha { get; set; }
        public string NomeCampanha { get; set; }
        public string MsgCampanha { get; set; }
        public byte[] ImgCampanha { get; set; }
        public string NomeImgCampanha { get; set; }
        public string ExtImgCampanha { get; set; }
        public Nullable<System.DateTime> DataCampanha { get; set; }
    }
}
