//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoardRepComercial.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JUNDSOFTEntities : DbContext
    {
        public JUNDSOFTEntities()
            : base("name=JUNDSOFTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_CD_25> T_CD_25 { get; set; }
        public virtual DbSet<T_FT_01> T_FT_01 { get; set; }
        public virtual DbSet<T_FT_02> T_FT_02 { get; set; }
        public virtual DbSet<T_SY_40> T_SY_40 { get; set; }
        public virtual DbSet<T_SY_42> T_SY_42 { get; set; }
        public virtual DbSet<T_SY_43> T_SY_43 { get; set; }
    }
}
