//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoardRepComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CD_25
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_CD_25()
        {
            this.T_FT_01 = new HashSet<T_FT_01>();
            this.T_FT_011 = new HashSet<T_FT_01>();
            this.T_SY_40 = new HashSet<T_SY_40>();
            this.T_SY_401 = new HashSet<T_SY_40>();
        }
    
        public string SY01_EMPRESA { get; set; }
        public string CD25_VENDEDOR { get; set; }
        public string CD34_GERENTE { get; set; }
        public string CD25_NOME { get; set; }
        public decimal CD25_COMISSAO { get; set; }
        public string CD25_PODE_ATRAV { get; set; }
        public string CD25_SERA_ATRAV { get; set; }
        public string CD25_ATIVO { get; set; }
        public string CD25_CGC_CPF { get; set; }
        public string CD25_INSC_EST { get; set; }
        public string CD25_INSC_MUN { get; set; }
        public string CD25_ENDERECO { get; set; }
        public string CD25_CIDADE { get; set; }
        public string CD25_BAIRRO { get; set; }
        public string CD25_CEP { get; set; }
        public string CD30_UF { get; set; }
        public string CD25_TELEFONE { get; set; }
        public string CD25_EMAIL { get; set; }
        public string CD25_FAX { get; set; }
        public string CD25_MOBILE_TEM { get; set; }
        public string CD25_MOBILE_EMAIL { get; set; }
        public string CD25_MOBILE_SENHA { get; set; }
        public string CD25_MOBILE_SO { get; set; }
        public string CD25_RECEBE_DANFE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_FT_01> T_FT_01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_FT_01> T_FT_011 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SY_40> T_SY_40 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SY_40> T_SY_401 { get; set; }
    }
}
