//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoardRepComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FT_02
    {
        public string SY01_EMPRESA { get; set; }
        public int FT01_NOTA { get; set; }
        public int FT02_ITEM { get; set; }
        public string CD14_SIGLA { get; set; }
        public decimal FT02_QTDE { get; set; }
        public decimal FT02_SALDO_TERC { get; set; }
        public decimal FT02_VLR_UN { get; set; }
        public decimal FT02_ALIQ_IPI { get; set; }
        public decimal FT02_ALIQ_ICMS { get; set; }
        public decimal FT02_ALIQ_SUBST { get; set; }
        public decimal FT02_ALIQ_ISS { get; set; }
        public decimal FT02_ALIQ_INSS { get; set; }
        public decimal FT02_ALIQ_IR { get; set; }
        public decimal FT02_ALIQ_PIS { get; set; }
        public decimal FT02_ALIQ_COFINS { get; set; }
        public decimal FT02_ALIQ_CSLL { get; set; }
        public decimal FT02_VLR_IPI { get; set; }
        public decimal FT02_VLR_ICMS { get; set; }
        public decimal FT02_VLR_SUBST { get; set; }
        public decimal FT02_VLR_ACESS { get; set; }
        public decimal FT02_VLR_ISS { get; set; }
        public decimal FT02_VLR_IR { get; set; }
        public decimal FT02_VLR_INSS { get; set; }
        public decimal FT02_VLR_PIS { get; set; }
        public decimal FT02_VLR_COFINS { get; set; }
        public decimal FT02_VLR_CSLL { get; set; }
        public decimal FT02_VLR_MERC { get; set; }
        public decimal FT02_VLR_TOTAL { get; set; }
        public decimal FT02_BASE_ICMS { get; set; }
        public decimal FT02_BASE_SUBST { get; set; }
        public decimal FT02_QTDE_BX_EST { get; set; }
        public decimal FT02_VLR_BX_EST { get; set; }
        public Nullable<decimal> FT02_CUSTO_INFORMADO { get; set; }
        public string FT02_CARIMBO { get; set; }
        public Nullable<int> FT02_NF_DEV { get; set; }
        public string FT02_NF_DEV_SERIE { get; set; }
        public Nullable<int> FT02_NF_DEV_ITEM { get; set; }
        public decimal FT02_ALIQ_PIS_FAT { get; set; }
        public decimal FT02_ALIQ_COFINS_FAT { get; set; }
        public decimal FT02_VLR_PIS_FAT { get; set; }
        public decimal FT02_VLR_COFINS_FAT { get; set; }
        public string CD10_ALMOX { get; set; }
        public string CD15_UNIDADE { get; set; }
        public string FT02_DESCRICAO { get; set; }
        public string FT02_CST { get; set; }
        public string CD19_POS_FISCAL { get; set; }
        public Nullable<int> PV01_PEDIDO { get; set; }
        public Nullable<int> PV02_ITEM { get; set; }
        public string CD21_INCIDENCIA { get; set; }
        public int CD20_COF { get; set; }
        public string CD04_MATERIAL { get; set; }
        public string ES10_LOTE { get; set; }
        public decimal FT02_ALIQ_ISS_FAT { get; set; }
        public decimal FT02_VLR_ISS_FAT { get; set; }
        public Nullable<decimal> FT02_VPC_PERCENTUAL { get; set; }
        public Nullable<decimal> FT02_VPC_VALOR { get; set; }
        public Nullable<decimal> FT02_VPC_BASE { get; set; }
        public string FT02_IMP_DI { get; set; }
        public Nullable<System.DateTime> FT02_IMP_DI_DATA { get; set; }
        public Nullable<int> FT02_IMP_ADICAO { get; set; }
        public Nullable<int> FT02_IMP_ADICAO_SEQ { get; set; }
        public decimal FT02_BASE_ICMS_SIMPLES { get; set; }
        public decimal FT02_VLR_ICMS_SIMPLES { get; set; }
        public decimal FT02_ALIQ_ICMS_SIMPLES { get; set; }
        public string FT02_CSOSN_SIMPLES { get; set; }
        public Nullable<decimal> FT02_IMP_VLR_PIS { get; set; }
        public Nullable<decimal> FT02_IMP_VLR_COFINS { get; set; }
        public Nullable<decimal> FT02_IMP_VLR_II { get; set; }
        public Nullable<decimal> FT02_IMP_VLR_SISCOMEX { get; set; }
        public Nullable<decimal> FT02_IMP_VLR_NAO_TRIB { get; set; }
        public decimal FT02_VLR_ICMS_DIF { get; set; }
        public decimal FT02_VLR_ICMS_DIF_PERC { get; set; }
        public Nullable<int> FT02_PED_CLI_IT { get; set; }
        public string FT02_CST_IPI { get; set; }
        public string FT02_CST_PIS { get; set; }
        public string FT02_CST_COFINS { get; set; }
        public decimal FT02_DESC_ICMS { get; set; }
        public decimal FT02_DESC_PISCOFINS { get; set; }
        public decimal FT02_RED_BASE_ICMS { get; set; }
        public decimal FT02_RED_BASE_SUBST { get; set; }
        public decimal FT02_IVA_SUBST { get; set; }
        public decimal FT02_ALIQ_TRIB_APROXIMADO { get; set; }
        public decimal FT02_VLR_TRIB_APROXIMADO { get; set; }
        public Nullable<decimal> FT02_EXTRAVIO_QTDE { get; set; }
        public string FT02_EXTRAVIO_MOTIVO { get; set; }
    
        public virtual T_FT_01 T_FT_01 { get; set; }
        public virtual T_FT_01 T_FT_011 { get; set; }
    }
}
