//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoardRepComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FT_01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_FT_01()
        {
            this.T_FT_02 = new HashSet<T_FT_02>();
            this.T_FT_021 = new HashSet<T_FT_02>();
        }
    
        public string SY01_EMPRESA { get; set; }
        public int FT01_NOTA { get; set; }
        public string CD14_SIGLA { get; set; }
        public int FT01_TIPO { get; set; }
        public string FT01_NATUREZA { get; set; }
        public int FT01_FRETE { get; set; }
        public string FT01_PLACA { get; set; }
        public string FT01_MARCA_EMBAL { get; set; }
        public int FT01_QTDE_EMBAL { get; set; }
        public decimal FT01_PESO_LIQUIDO { get; set; }
        public decimal FT01_PESO_BRUTO { get; set; }
        public string FT01_OBS_NF { get; set; }
        public string FT01_OBS_SUF { get; set; }
        public string FT01_OBS_ENTREGA { get; set; }
        public System.DateTime FT01_DATA_EMISSAO { get; set; }
        public System.DateTime FT01_DATA_DIG { get; set; }
        public Nullable<System.DateTime> FT01_DATA_EMB { get; set; }
        public Nullable<System.DateTime> FT01_DATA_ENTREGA { get; set; }
        public string FT01_MINUTA { get; set; }
        public string FT01_IMPRESSA { get; set; }
        public string FT01_CANCELADA { get; set; }
        public string FT01_HIST_CANC { get; set; }
        public Nullable<System.DateTime> FT01_DATA_CANC { get; set; }
        public Nullable<System.DateTime> FT01_COMPET_INI { get; set; }
        public Nullable<System.DateTime> FT01_COMPET_FIM { get; set; }
        public string FT01_PED_CLI { get; set; }
        public decimal FT01_VLR_PIS { get; set; }
        public decimal FT01_VLR_COFINS { get; set; }
        public string SY42_USUARIO { get; set; }
        public string CD06_CGC_FOR { get; set; }
        public string CD26_COND_PAG { get; set; }
        public int CD20_COF { get; set; }
        public string CD08_CGC_CLI { get; set; }
        public string CD70_CODIGO { get; set; }
        public System.DateTime CT01_DATA_CONTABIL { get; set; }
        public Nullable<int> CT01_LANCAMENTO { get; set; }
        public string CD25_VENDEDOR { get; set; }
        public string CD30_UF { get; set; }
        public string FT01_NOME_CLIENTE { get; set; }
        public string FT01_TELEFONE { get; set; }
        public string FT01_ENDERECO { get; set; }
        public string FT01_BAIRRO { get; set; }
        public string FT01_CIDADE { get; set; }
        public string FT01_CEP { get; set; }
        public string FT01_DOCUMENTO { get; set; }
        public string FT01_CHEQUE { get; set; }
        public string FT01_NUMERO_SEDEX { get; set; }
        public string FT01_REFERENCIA { get; set; }
        public string FT01_NFE_CHAVE { get; set; }
        public string CD42_ORIGEM { get; set; }
        public Nullable<int> OR01_ORDEM { get; set; }
        public Nullable<int> FT01_NFE_STATUS { get; set; }
        public string FT01_NFE_PROT { get; set; }
        public Nullable<System.DateTime> FT01_NFE_PROT_DATA { get; set; }
        public string FT01_NFE_PROT_CANC { get; set; }
        public Nullable<System.DateTime> FT01_NFE_PROT_CANC_DATA { get; set; }
        public string FT01_NFE_MOT_REJEICAO { get; set; }
        public string FT01_NFE_RECIBO_LOTE { get; set; }
        public string FT01_NFE_XML_ENVIADO { get; set; }
        public string FT01_NFE_CHAVE_NF_COMP { get; set; }
        public Nullable<int> SY75_ID { get; set; }
        public string FT01_NOTA_VCHAR { get; set; }
        public string FT01_CARTAO_SEDEX { get; set; }
        public Nullable<System.DateTime> FT01_DATA_CANHOTO { get; set; }
        public string FT01_WMS_BAIXADO { get; set; }
        public Nullable<System.DateTime> FT01_ENT_AG_DATA { get; set; }
        public Nullable<System.DateTime> FT01_ENT_AG_DATA_H { get; set; }
        public string FT01_ENT_AG_OBS { get; set; }
        public Nullable<System.DateTime> FT01_ENT_AG_DIG { get; set; }
        public Nullable<System.DateTime> FT01_ENT_AG_DIG_H { get; set; }
        public string FT01_ENT_AG_USUARIO { get; set; }
        public Nullable<System.DateTime> FT01_ENT_SOLIC_RET { get; set; }
        public Nullable<System.DateTime> FT01_ENT_DEVOLUCAO { get; set; }
        public string FT01_NFE_DENEGADA { get; set; }
        public string FT01_ESPECIE_EMBAL { get; set; }
        public string FT01_NUMERO_EMBAL { get; set; }
        public Nullable<System.DateTime> FT01_DATA_BASE { get; set; }
        public Nullable<int> PC20_PROCESSO { get; set; }
        public Nullable<int> PC20_ANO { get; set; }
        public string FT01_NFE_PROCESS { get; set; }
        public Nullable<int> CD08A_ID { get; set; }
        public string FT01_PI_PROT { get; set; }
        public Nullable<System.DateTime> FT01_PI_DATA { get; set; }
        public Nullable<int> FT01_NF_REMESSA { get; set; }
        public string FT01_NF_REMESSA_SERIE { get; set; }
    
        public virtual T_CD_25 T_CD_25 { get; set; }
        public virtual T_CD_25 T_CD_251 { get; set; }
        public virtual T_SY_42 T_SY_42 { get; set; }
        public virtual T_SY_42 T_SY_421 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_FT_02> T_FT_02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_FT_02> T_FT_021 { get; set; }
    }
}
