//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoardRepComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SY_42
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_SY_42()
        {
            this.T_FT_01 = new HashSet<T_FT_01>();
            this.T_FT_011 = new HashSet<T_FT_01>();
            this.T_SY_43 = new HashSet<T_SY_43>();
            this.T_SY_431 = new HashSet<T_SY_43>();
        }
    
        public string SY42_USUARIO { get; set; }
        public string SY42_NOME { get; set; }
        public string SY42_SENHA { get; set; }
        public Nullable<decimal> SY42_LIMITE_PC { get; set; }
        public Nullable<decimal> SY42_LIMITE_PV { get; set; }
        public string SY42_ATIVO { get; set; }
        public string SY42_MAN_FORNECEDOR { get; set; }
        public string SY42_MAN_CLIENTE { get; set; }
        public string SY42_MAN_CLIENTE_CREDITO { get; set; }
        public string SY42_MAN_CLIENTE_ENTCOB { get; set; }
        public string SY42_MAN_CLIENTE_CONTATOS { get; set; }
        public string SY42_DIGITA_PC { get; set; }
        public string SY42_DIR_TEXTO { get; set; }
        public string SY42_MAN_CLIENTE_TABELA { get; set; }
        public string SY42_EMAIL { get; set; }
        public decimal SY42_LIMITE_PV_DESC { get; set; }
        public string SY42_SERVIDOR_SMTP { get; set; }
        public string SY42_SERVIDOR_USUARIO { get; set; }
        public string SY42_SERVIDOR_SENHA { get; set; }
        public Nullable<int> SY42_SERVIDOR_PORTA { get; set; }
        public Nullable<bool> SY42_SERVIDOR_SSL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_FT_01> T_FT_01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_FT_01> T_FT_011 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SY_43> T_SY_43 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SY_43> T_SY_431 { get; set; }
    }
}
