//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoardRepComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SY_43
    {
        public string SY01_EMPRESA { get; set; }
        public string SY42_USUARIO { get; set; }
        public string SY40_GRUPO { get; set; }
    
        public virtual T_SY_40 T_SY_40 { get; set; }
        public virtual T_SY_40 T_SY_401 { get; set; }
        public virtual T_SY_42 T_SY_42 { get; set; }
        public virtual T_SY_42 T_SY_421 { get; set; }
    }
}
