//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoardRepComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SY_40
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_SY_40()
        {
            this.T_SY_43 = new HashSet<T_SY_43>();
            this.T_SY_431 = new HashSet<T_SY_43>();
        }
    
        public string SY01_EMPRESA { get; set; }
        public string SY40_GRUPO { get; set; }
        public string SY40_DESCRICAO { get; set; }
        public int SY40_TIPO { get; set; }
        public string CD25_VENDEDOR { get; set; }
        public string CD55_FABRICANTE { get; set; }
        public string CD08_CGC_CLI { get; set; }
        public string CD34_GERENTE { get; set; }
        public string CD67_DIRETOR { get; set; }
    
        public virtual T_CD_25 T_CD_25 { get; set; }
        public virtual T_CD_25 T_CD_251 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SY_43> T_SY_43 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SY_43> T_SY_431 { get; set; }
    }
}
