//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoardRepComercial.Models
{
    using System;
    
    public partial class Ults_Fats_GerReg : Ults_Fats_Vend_Result
    {
        public string Vendedor { get; set; }
    }
}
